2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_setup.py:_flush():76] Configure stats pid to 7465
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_setup.py:_flush():76] Loading settings from /home/sarthak/.config/wandb/settings
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_setup.py:_flush():76] Loading settings from /home/sarthak/github-classroom/Statistical-Methods-in-AI-Monsoon-2023/assignment-3-sarthakchittawar/wandb/settings
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'uncategorized', 'entity': 'sarthakchittawar', 'root_dir': '/home/sarthak/github-classroom/Statistical-Methods-in-AI-Monsoon-2023/assignment-3-sarthakchittawar', 'sweep_id': 'xy248zi0', 'run_id': 'nx75xh0p', 'sweep_param_path': '/home/sarthak/github-classroom/Statistical-Methods-in-AI-Monsoon-2023/assignment-3-sarthakchittawar/wandb/sweep-xy248zi0/config-nx75xh0p.yaml'}
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_init.py:_log_setup():528] Logging user logs to /home/sarthak/github-classroom/Statistical-Methods-in-AI-Monsoon-2023/assignment-3-sarthakchittawar/wandb/run-20231016_020115-nx75xh0p/logs/debug.log
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_init.py:_log_setup():529] Logging internal logs to /home/sarthak/github-classroom/Statistical-Methods-in-AI-Monsoon-2023/assignment-3-sarthakchittawar/wandb/run-20231016_020115-nx75xh0p/logs/debug-internal.log
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_init.py:_jupyter_setup():474] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f603a026050>
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():568] calling init triggers
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():575] wandb.init called with sweep_config: {'activation_func': 'sigmoid', 'hidden_layers': [6, 6], 'lr': 0.001, 'optimizer': 'sgd'}
config: {}
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():618] starting backend
2023-10-16 02:01:15,833 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():622] setting up manager
2023-10-16 02:01:15,839 INFO    Thread-6 (_run_job):7465 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-16 02:01:15,841 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():628] backend started and connected
2023-10-16 02:01:15,846 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_config_callback():1324] config_cb None None {'activation_func': 'sigmoid', 'hidden_layers': [6, 6], 'lr': 0.001, 'optimizer': 'sgd'}
2023-10-16 02:01:15,847 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_label_probe_notebook():1276] probe notebook
2023-10-16 02:01:15,847 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_label_probe_notebook():1286] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-10-16 02:01:15,847 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():720] updated telemetry
2023-10-16 02:01:15,855 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-16 02:01:16,660 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_on_init():2220] communicating current version
2023-10-16 02:01:16,804 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_on_init():2229] got version response 
2023-10-16 02:01:16,804 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():804] starting run threads in backend
2023-10-16 02:01:21,843 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_console_start():2199] atexit reg
2023-10-16 02:01:21,843 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-16 02:01:21,843 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-16 02:01:21,843 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-16 02:01:21,844 INFO    Thread-6 (_run_job):7465 [wandb_init.py:init():845] run started, returning control to user process
2023-10-16 02:01:33,558 INFO    MainThread:7465 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-16 02:01:33,573 INFO    MainThread:7465 [wandb_init.py:_pause_backend():438] pausing backend
2023-10-16 02:02:54,612 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_finish():1934] finishing run sarthakchittawar/uncategorized/nx75xh0p
2023-10-16 02:02:54,612 ERROR   Thread-6 (_run_job):7465 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-10-16 02:02:54,613 INFO    Thread-6 (_run_job):7465 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-10-16 02:02:54,613 INFO    Thread-6 (_run_job):7465 [wandb_init.py:_jupyter_teardown():456] cleaning up jupyter logic
2023-10-16 02:02:54,613 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_atexit_cleanup():2168] got exitcode: 1
2023-10-16 02:02:54,613 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_restore():2151] restore
2023-10-16 02:02:54,613 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_restore():2157] restore done
2023-10-16 02:02:54,614 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_restore():2151] restore
2023-10-16 02:02:54,614 INFO    Thread-6 (_run_job):7465 [wandb_run.py:_restore():2157] restore done
2023-10-16 02:02:55,618 ERROR   Thread-6 (_run_job):7465 [wandb_run.py:_atexit_cleanup():2189] Problem finishing run
Traceback (most recent call last):
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 298, in _run_job
    self._function()
  File "/tmp/ipykernel_7465/3168985798.py", line 26, in my_train_func
    wandb.log({"train_mse": train_mse[i], "val_mse": val_mse[i], "train_rmse": train_rmse[i], "val_rmse": val_rmse[i], "train_r2": train_r2[i], "val_r2": val_r2[i], "epochs": i+1, "lr": lr, "activation_func": activation_func, "optimizer": optimizer, "hidden_layers": hidden_layers})
                                                                                                                                   ~~~~~~~~^^^
IndexError: invalid index to scalar variable.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2177, in _atexit_cleanup
    self._on_finish()
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 2412, in _on_finish
    self._footer_exit_status_info(
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 3397, in _footer_exit_status_info
    printer.display(f'{" ".join(info)}')
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/wandb/sdk/lib/printer.py", line 68, in display
    self._display(text, level=level, default_text=default_text)
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/wandb/sdk/lib/printer.py", line 247, in _display
    self._display_fn_mapping(level)(text)
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/wandb/sdk/lib/ipython.py", line 81, in display_html
    return display(HTML(html))
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/IPython/core/display_functions.py", line 305, in display
    publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/IPython/core/display_functions.py", line 93, in publish_display_data
    display_pub.publish(
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 102, in publish
    self._flush_streams()
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 65, in _flush_streams
    sys.stdout.flush()
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/ipykernel/iostream.py", line 559, in flush
    self.pub_thread.schedule(self._flush)
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/ipykernel/iostream.py", line 251, in schedule
    self._event_pipe.send(b"")
  File "/home/sarthak/miniconda3/envs/smai/lib/python3.11/site-packages/zmq/sugar/socket.py", line 696, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/socket.pyx", line 742, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 138, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket
